#!/bin/sh
# Make sure the system's certificates are valid for the active config

set -e

PRIVKEY="/etc/ssl/private/server-private.key"
CERT="/etc/ssl/certs/server.crt"

# TODO(bluecmd): Check CN, check validity and stuff like that
if [ -f "${PRIVKEY}" ] && [ -f "${CERT}" ]; then
  exit 0
fi

install -d -m=750 -o root -g root /etc/ssl/private

CSR=$(mktemp)
openssl genrsa -out "${PRIVKEY}" 2048
openssl req -new -key "${PRIVKEY}" -out "${CSR}" \
  -subj "/C=US/ST=California/L=San Francisco/O=LibreSwitch"

openssl x509 -req -days 14600 -in "${CSR}" -signkey "${PRIVKEY}" -out "${CERT}"

rm -f ${CSR}
