#!/bin/sh

if [ x$reason = xBOUND ] || [ x$reason = xRENEW ]; then
	if [ -n "${new_openswitch_ztp+x}" ]; then
                autoprovision ${new_openswitch_ztp}
	fi

fi

dhcphostname ${new_host_name}
