# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$provisioning_script = <<SCRIPT
export http_proxy=http://web-proxy.americas.hpqcorp.net:8080
export https_proxy=http://web-proxy.americas.hpqcorp.net:8080
sudo -E apt-get update
sudo -E apt-get upgrade
sudo -E apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib  build-essential chrpath screen curl device-tree-compiler xterm aptitude
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = ENV['USER'] + "_dev"

  # Make the machine appear as another machine in the network
  config.vm.network "public_network"
  # Create a private network used for NFS shared folders
  config.vm.network "private_network", type: "dhcp"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ENV['HOME'], ENV['HOME'], type: "nfs"

  config.vm.provider "virtualbox" do |vb|
     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
#  config.vm.provision "shell", inline: $provisioning_script
end
