# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$provisioning_script = <<SCRIPT
export http_proxy=$1
export https_proxy=$2
sudo -E apt-get update
sudo -E apt-get -y upgrade
# Required for windows integration
sudo -E apt-get -y install smbclient cifs-utils
# Required by yocto
sudo -E apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib  build-essential chrpath screen curl device-tree-compiler xterm aptitude
SCRIPT

module OS
  def OS.windows?
    (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end
end

if OS.windows? then
  $user = ENV['USERNAME']
  $home = ENV['HOMEPATH']
  $homemounttype = "smb"
else
  $user = ENV['USER']
  $home = ENV['HOME']
  $homemounttype = "nfs"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = $user + "-dev"

  # Make the machine appear as another machine in the network
  config.vm.network "public_network"
  # Create a private network used for NFS shared folders
  config.vm.network "private_network", type: "dhcp"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder $home, "/home/" + $user, type: $homemounttype 

  config.vm.provider "virtualbox" do |vb|
     vb.name = $user + "-dev"
     vb.memory = 2048
     vb.cpus = 4
  end
  config.vm.provision "shell" do |s|
    s.inline = $provisioning_script
    s.args = ENV['http_proxy'], ENV['https_proxy']
  end
end
